name: Test and Merge to Develop
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - test/develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: granos_de_oro_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Configure environment variables
        run: |
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=granos_de_oro_test" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Wait for MySQL
        run: sleep 60 # Aumentar el tiempo de espera

      - name: Clear Laravel config cache
        run: |
          php artisan config:cache
          php artisan cache:clear

      - name: Run migrations
        run: php artisan migrate

      - name: Run tests
        run: php artisan test

      - name: Install GitHub CLI
        if: success()
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Merge to develop if tests pass
        if: success()
        run: |
          # Configuración inicial
          git config --global user.email "jose.carlos.silva@correounivalle.edu.co"
          git config --global user.name "CarlosR99"

          # Crear rama temporal para el PR
          BRANCH_NAME="merge-pedido-resource-$(date +%s)"
          git checkout -b $BRANCH_NAME

          # Realizar cambios en rama temporal
          git fetch origin refactor/PedidoResource:refactor/PedidoResource || exit 1
          git merge refactor/PedidoResource --no-ff -m "Merge refactor/PedidoResource into develop"

          # Push rama temporal
          git remote set-url origin https://CarlosR99:${{ secrets.TOKEN }}@github.com/jumahl/granosdeoro.git
          git push origin $BRANCH_NAME

          # Crear PR usando GitHub CLI
          gh auth login --with-token <<< "${{ secrets.TOKEN }}"
          PR_URL=$(gh pr create \
            --base develop \
            --head $BRANCH_NAME \
            --title "[Automated] Merge refactor/PedidoResource into develop" \
            --body "Este PR requiere 2 revisiones antes de ser fusionado con develop.
            
            - [ ] Revisión 1
            - [ ] Revisión 2" \
            --label "automated-pr" \
            --reviewer "reviewer1,reviewer2")
            
          echo "PR creado en: $PR_URL"
